# Generated by Django 4.2.2 on 2023-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_usuario_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_publicada',
            new_name='data_fotografia',
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
