# Generated by Django 4.2.2 on 2023-06-16 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicada',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
