# Generated by Django 4.2.2 on 2023-06-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_publicada_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_publicada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
